default_agent: agentcore_starter_strands
agents:
  agentcore_starter_strands:
    name: agentcore_starter_strands
    entrypoint: /Users/kevinlupera/dev/bedrock/agentcore-aws-ec/agentcore_starter_strands.py
    platform: linux/arm64
    container_runtime: finch
    source_path: /Users/kevinlupera/dev/bedrock/agentcore-aws-ec
    aws:
      execution_role: arn:aws:iam::600627330313:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-9c0804ec0c
      execution_role_auto_create: false
      account: '600627330313'
      region: us-east-1
      ecr_repository: 600627330313.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_starter_strands
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_starter_strands-w3tPCd59GI
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:600627330313:runtime/agentcore_starter_strands-w3tPCd59GI
      agent_session_id: d266ac20-791d-487e-a564-83e348d5dc17
    codebuild:
      project_name: bedrock-agentcore-agentcore_starter_strands-builder
      execution_role: arn:aws:iam::600627330313:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-9c0804ec0c
      source_bucket: bedrock-agentcore-codebuild-sources-600627330313-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: agentcore_starter_strands_mem-Csdh3kFxAd
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:600627330313:memory/agentcore_starter_strands_mem-Csdh3kFxAd
      memory_name: agentcore_starter_strands_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
